GET http://localhost:5000/api/v1/user/djiksmdx

###
POST http://localhost:5000/api/v1/auth/register
Content-Type: application/json

{
    "name": "Admin01",
    "email": "admin01@gmail.com",
    "phone": "0123456789",
    "address": "Da Nang",
    "password": "123456",
    "role_code": "R3"
}

###

POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
    "email": "user07@gmail.com",
    "password": "123456"
}

###
GET http://localhost:5000/api/v1/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsImVtYWlsIjoidXNlcjAxQGdtYWlsLmNvbSIsInJvbGVfY29kZSI6IlIzIiwiaWF0IjoxNjkyMDIxNjkzLCJleHAiOjE2OTI0NTM2OTN9.eef39QdHnK2ssFUtQAv4xCZsOQrKtmtAcUl6UVnSHEE

###

GET http://localhost:5000/api/v1/insert/

###

GET http://localhost:5000/api/v1/bookLists/?id=5

###

GET http://localhost:5000/api/v1/category/

###

POST http://localhost:5000/api/v1/cart
Content-Type: application/json

{
    "2": 1,
    "4": 2
}
